### PR TITLE
fix path to tests in MANIFEST.in

### PR DESCRIPTION
**Pull request by danc86**
This will include the tests in the source tarball once again.

### CODE REVIEW

**Comment by adamchainz** [comment]
Why do you want the tests in the tarball? I've been thinking of stopping shipping them, and instead leaving the github tarballs as the way of getting at them ( https://github.com/pytest-dev/pytest-randomly/releases ) . I only run the tests with tox and don't want to make any promises they work in other cases.

**Comment by danc86** [comment]
I'm packaging this project for Fedora and I want to run the tests as part of the build process.

I'll just note that the tests *are* currently supposed to be included:
https://github.com/pytest-dev/pytest-randomly/commit/e19ae9976cb9e60100b9f55063b1f2414db2ddf8

but another rearrangement of the source tree means that the current MANIFEST.in entry is pointing at the wrong path (and is then silently ignored by setuptools, I guess).

**Comment by adamchainz** [comment]
Released in version 3.2.1: https://pypi.org/project/pytest-randomly/3.2.1/

I'd still recommend moving to the GitHub tarballs since they include every file in the repo and you should be able to just copy and run `tox`.

Honest question, not being flippant: why bother with all the effort repackaging? Seems like a lot of effort for little reward to me. I also think it's better for the Python ecosystem to encourage users to use Pip.

**Comment by adamchainz** [comment]
Released in version 3.2.1: https://pypi.org/project/pytest-randomly/3.2.1/

I'd still recommend moving to the GitHub tarballs since they include every file in the repo and you should be able to just copy and run `tox` for the tests.

Honest question, not being flippant: why bother with all the effort repackaging? Seems like a lot of effort for little reward to me. I also think it's better for the Python ecosystem to encourage users to use Pip.

**Comment by danc86** [comment]
Thanks for that.

Of course if you prefer to distribute sources through Github tarballs instead of PyPI that is totally up to you. If you do decide to go that direction I would suggest that you stop uploading source tarballs to PyPI though.

There seems to be an increasing trend in our ecosystem towards treating the sdists uploaded to PyPI as some kind of pre-built binary distribution to be consumed only by `pip install`, but that is not really what they are for. It's even in the name: sdist stands for _source distribution_ and to me that means the _complete_ sources, including everything needed to build the package like its test suite. PyPI was originally built as a _source_ hosting platform though of course for many years now it has also supported bdists. I guess in the Python ecosystem many people don't make the distinction between sdist and bdist, if their package is pure Python and does not require any compilation step. Or maybe it's because `pip install` never runs the tests and just leaves the user to hope the package actually works in their environment so people don't consider the test suite to be needed for the build process? But treating PyPI sdists that way is confusing because it breaks the expectations of what an sdist is, when some random stranger on the internet (like me) comes along and downloads it expecting it to contain the complete sources for a release.

As for why bother packaging Python projects in Linux distros... well that essentially boils down to "why should Linux distros exist at all" :-) which is probably off-topic and a larger issue than can be discussed here...

But if it helps: I prefer to obtain Python packages from my distro for the same reason I prefer to obtain all the other code I use on my system from my distro. For one thing, I find it easier to use a single package manager for everything. But more importantly, the distro provides strong policies and tools to ensure everything (Python or otherwise) is built cleanly, reproducibly, in a consistent way, installs into consistent places, and stays compatible within a release cycle. Maintaining a distro package is much more than just grabbing the source files and jamming them into an RPM package. If you've never maintained a distro package you might not realise how much effort goes into them.

**Comment by adamchainz** [comment]
Thanks for taking the time to write such a long reply.

> I guess in the Python ecosystem many people don't make the distinction between sdist and bdist

Yeah I guess this comes with being an interpreted language.

> maybe it's because pip install never runs the tests and just leaves the user to hope the package actually works in their environment so people don't consider the test suite to be needed for the build process?

Tbh I don't think across all the ~20 Python packages I've personally maintained, I've seen any bug that would have been caught by running the test suite on install. Also for several of my packages, it'd be very hard to make it runnable at install time (at least with current tooling) e.g. on Django-MySQL a supported MySQL server is needed with permissions for the local user to connect and create a test database (which won't be dropped if the tests fail, because that's how Django does it).

> If you've never maintained a distro package you might not realise how much effort goes into them.

I understand they're a lot of effort, that's one of the reasons I asked :)

Thanks,

Adam
Also I guess there's no clear answer to "is the test suite part of the source?" - just community norms.

**Pull request merged**
