### PR TITLE
Add force-reorganize feature

### PR DESCRIPTION
**Pull request by zubchick**
Sometimes you have to set seed but still want to reorganize tests. Now you can do it with `--randomly-force-reorganize` flag.

### CODE REVIEW

**Comment by adamchainz** [comment]
So despite the seed being set, you want to use a different seed to reorganize the tests again? Can you explain your use case a bit more, I'm not sure I understand when you'd want to do this.

**Comment by zubchick** [comment]
I have lots of tests that depend on fixed seed but I don't want to set seed for every test by hand.

**Comment by adamchainz** [comment]
Your tests shouldn't depend on a fixed seed, that's the point of this library, to re-randomize at each run. If your tests depend on fixed data, they should encode that data themselves rather than use `random` to generate it? If you can't do this, could you not create a separate `random.Random` with your fixed seed for your test data generation to feed off?

**Comment by zubchick** [comment]
I have a few correct answers for the same input and I randomly pick one.

```python

def f(x):
    return random.choice(data[x])

def test_f():
    assert f(1) == 345
    assert f(2) == 432
```

**Comment by adamchainz** [comment]
I think such tests would be better making assertions like `assert f(1) in data[1]` in cases like that. The main use case I see for pytest-randomly is using random test data generators - not for testing algorithms that return different results randomly. If there are a wide range of valid return values for a function, you should probably have an assertion that covers that range, rather than freezing to a specific case. If Python's random algorithm changes, or some minor part about the arrangement of your data underneath is refactored, all your very-specific tests will break.

Also I don't think this current PR is a great idea as it's adding another flag for your very specific use case and it has unconsidered interactions with the other options. Like, what should happen when combined with `--randomly-dont-reorganize` - should we error, or one should be marked as taking priority? And what if a user finds an error that depends on a specific random seed AND THEN a specific order of test execution? It's now out of control with this flag, it woudl then require a second optional random seed for controlling just the test order, ...

**Comment by adamchainz** [comment]
closing due to no response

**Pull request closed without merging**
