### PR TITLE
Document how to get seed value in a test case

### PR DESCRIPTION
**Pull request by hukkinj1**

### CODE REVIEW

**Comment by adamchainz** [comment]
Can you explain why you'd want to do this a bit? Also I think this should be moved much later in the docs, perhaps in a section after "entry point".

**Comment by hukkinj1** [comment]
I was looking for a way to get reproducible randomness independent of how many / which tests are selected for a pytest run. I didn't realize that this can be achieved simply by using any function from the `random` stdlib due to the fact that `pytest-randomly` resets to the same random state at the start of each test case.

So now I can't think of any reason to merge or do this. :smile:  In case you can't either, please close!

**Comment by hukkinj1** [comment]
I now noticed there is an old open issue about this topic https://github.com/pytest-dev/pytest-randomly/issues/192

Perhaps it should be closed as well if we can't think of a reason why accessing `randomly_seed` can be useful ?

**Comment by adamchainz** [comment]
> In case you can't either, please close!

Yes same, and I'm closing that issue.

**Pull request closed without merging**
